version: 0.0
os: linux
files:
  - source: monolithic-java-webapp.jar
    destination: /app
hooks:
  BeforeInstall:
    - location: install_dependencies.sh
      timeout: 120
      runas: root
  ApplicationStart:
    - location: start_server.sh
      timeout: 120
      runas: root
  ApplicationStop:
    - location: stop_server.sh
      timeout: 120
      runas: root